#!/usr/bin/env bash
# Install nginx and configure redirection



# Update the default Nginx configuration file to include the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart Nginx to apply the changes
sudo service nginx restart

# Verify if Nginx is serving the correct content
curl -I localhost/redirect_me
