#!/usr/bin/env bash
# Install nginx and configure redirection

# Update package list and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Configure Nginx to serve "Hello World!" at the root and add redirection
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Update the default Nginx configuration file to include the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart Nginx to apply the changes
sudo service nginx restart
