#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.8.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend iflames.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 473056-web-01 35.153.79.157:80
        server 473056-web-02 100.26.132.241:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
