#!/usr/bin/env bash
# This script terminates "4-to_infinity_and_beyond"

PID=$(pgrep -f '4-to_infinity_and_beyond')

if [ -z "$PID" ]; then
    echo "No matching process found."
else
    kill "$PID"
fi
