#!/usr/bin/env bash
# This script  that displays the content of the file /etc/passwd
# Script only displays: username, user id, home directory path for the user


file="/etc/passwd"
IFS=":"

if [ -f "$file" ]; then
    while read -r username uid home; do
        echo "$username:$uid:$home"
    done < "$file"
else
    echo "File $file does not exist."
fi