#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
	if [ -f "$file" ]; then
		name=$(echo "$file" | cut -d'-' -f 2-)
		echo "$name"
	fi
done
